{"name": "test_login_invalid_password", "status": "passed", "start": 1754560177254, "stop": 1754560178234, "uuid": "e41511f4-3d83-4dfa-b5ec-fc2693b0ee83", "historyId": "c6b3ee9e25d938de7eea45f2792e29d5", "testCaseId": "c6b3ee9e25d938de7eea45f2792e29d5", "fullName": "secure-auth-api.tests.test_auth.TestUserLogin#test_login_invalid_password", "labels": [{"name": "parentSuite", "value": "secure-auth-api.tests"}, {"name": "suite", "value": "test_auth"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "DESKTOP-32KVTAU"}, {"name": "thread", "value": "19728-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "secure-auth-api.tests.test_auth"}], "titlePath": ["secure-auth-api", "tests", "test_auth.py", "TestUserLogin"]}